-- Audit log for admin actions (create/reset/role changes)
-- Run in Supabase SQL editor (schema public)

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  action text not null,
  actor_username text,
  actor_role text,
  target_username text,
  target_role text,
  target_lab_id text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists audit_log_ts_idx on public.audit_log (ts desc);
create index if not exists audit_log_action_idx on public.audit_log (action);
create index if not exists audit_log_target_idx on public.audit_log (target_username);

-- Optional: enable RLS (recommended). The Streamlit app will write using service_role.
alter table public.audit_log enable row level security;

do $$
begin
  -- Allow service_role full access
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='audit_log' and policyname='service_role_all'
  ) then
    create policy service_role_all on public.audit_log
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;

-- Optional: allow admin users to read logs via anon/authenticated if you later use JWT-based RLS.
-- For now, keep it strict (service_role only).
